import { ProjectStatus } from '../ProjectStatus';
import { ProjectEvent } from '../ProjectEvents';
import { ProjectAttachmentRequired } from '../ProjectAttachmentsRequired';
import { ProjectAttachment } from '../ProjectAttachments';
import { User } from '../Users';

export interface Project {
    id: string;
    customer: string;
    document: string;
    phone: string;
    cellphone: string;
    contacts: string;
    email: string;
    zip_code: string;
    street: string;
    number: string;
    neighborhood: string;
    complement: string;
    city: string;
    state: string;
    coordinates: string;
    capacity: string;
    inversor: string;
    roof_orientation: string;
    roof_type: string;
    price: number;
    seler: string;
    notes: string;
    financier_same: boolean;
    financier: string;
    financier_document: string;
    financier_rg: string;
    financier_cellphone: string;
    financier_email: string;
    financier_zip_code: string;
    financier_street: string;
    financier_number: string;
    financier_neighborhood: string;
    financier_complement: string;
    financier_city: string;
    financier_state: string;
    created_by: string;
    created_at: Date;
    updated_by: string;
    updated_at: Date;
    seller_id: User;
    status: ProjectStatus;
    events: ProjectEvent[];
    attachmentsRequired: ProjectAttachmentRequired[];
    attachments: ProjectAttachment[];
}