import { EstimateStatus } from '../EstimateStatus';
import { User } from '../Users';
import { Store } from '../Stores'
import { Panel } from '../Panels';
import { RoofType } from '../RoofTypes';
import { RoofOrientation } from '../RoofOrientations';
import { EstimateItem } from '../EstimateItems';

export interface Estimate {
    id: string;
    customer: string;
    customer_from: 'site' | 'social' | 'customer' | 'internet' | 'street';
    document: string;
    phone: string;
    cellphone: string;
    contacts: string;
    email: string;
    zip_code: string;
    street: string;
    number: string;
    neighborhood: string;
    complement: string;
    city: string;
    state: string;
    energy_company: string;
    unity: string;
    kwh: number;
    irradiation: number;
    month_01: number;
    month_02: number;
    month_03: number;
    month_04: number;
    month_05: number;
    month_06: number;
    month_07: number;
    month_08: number;
    month_09: number;
    month_10: number;
    month_11: number;
    month_12: number;
    month_13: number;
    average_increase: number;
    discount_percent: boolean;
    discount: number;
    increase_percent: boolean;
    increase: number;
    show_values: boolean;
    show_discount: boolean;
    notes: string;
    created_by: string;
    created_at: Date;
    updated_by: string;
    updated_at: Date;
    user: User;
    store: Store;
    panel: Panel;
    roof_orientation: RoofOrientation;
    roof_type: RoofType;
    status: EstimateStatus;
    items: EstimateItem[];
}